import pygame

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

SCREEN_CENTER_X = SCREEN_WIDTH / 2
SCREEN_CENTER_Y = SCREEN_HEIGHT / 2 

SCREEN_SIZE = pygame.Rect((0, 0, SCREEN_WIDTH, SCREEN_HEIGHT))
TILE_SIZE = 32 
FPS = 60